### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by cocorini** [HARl803/community-service#2]
## Description
- 쿠키에 담겨있는 JSESSIONID를 가진채로 `auth서버의 URL: https://i11a803.p.ssafy.io/api/v1/auth/profile` 에 GET요청을 보내 profileId 받기

## Todo
- [x] auth 와 관련된 `authService`를 구현합니다.
    - [x] RestTemplate의 exchange 메서드 이용
    - [x] RestTemplate을 autoConfig에서 bean 등록
