### ISSUE TITLE
Error 처리

### ISSUE THREAD

**Issue by cocorini** [HARl803/community-service#4]
## Description
- 커스텀 에러 처리에 관한 부분 작성

## Todo
- [x] custom에러 코드 작성
- [ ] 에러처리를 위한 핸들러 클래스 생성
- [ ] 아마존에 용량 제한된 이미지를 올리기 위한 커스텀 에러 클래스 생성

## Etc
